import './globals.css'


export const metadata = {
  title: 'Dev. Portfolio',
  description: 'Generated by Moeen Dev.',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body 
        className={`bg-black ${process.env.NODE_ENV === "development" ? "debug-screens" : ""}`}
      >{children}</body>
    </html>
  )
}
